// frontend/src/app/shared/ui/base/button.component.ts
import { NgClass } from '@angular/common';
import { ChangeDetectionStrategy, Component, computed, input } from '@angular/core';

type ButtonVariant = 'primary' | 'secondary' | 'outline' | 'ghost';
type ButtonSize = 'sm' | 'md' | 'lg';

@Component({
  selector: 'app-button',
  imports: [NgClass],
  template: `
    <button
      [attr.type]="type()"
      [disabled]="disabled()"
      [attr.aria-disabled]="disabled() ? 'true' : null"
      [ngClass]="classes()"
    >
      <ng-content />
    </button>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ButtonComponent {
  readonly variant = input<ButtonVariant>('primary');
  readonly size = input<ButtonSize>('md');
  readonly block = input(false);
  readonly disabled = input(false);
  readonly type = input<'button' | 'submit' | 'reset'>('button');

  protected readonly classes = computed(() => {
    const base =
      'inline-flex items-center justify-center gap-2 font-bold transition focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-shop-primary focus-visible:ring-offset-2 focus-visible:ring-offset-white disabled:cursor-not-allowed disabled:opacity-60';
    const variants: Record<ButtonVariant, string> = {
      primary: 'bg-shop-primary text-shop-text-inverted shadow-[0_18px_34px_rgba(37,99,235,0.22)] hover:bg-shop-primary-hover',
      secondary:
        'bg-shop-secondary text-shop-text-inverted shadow-[0_18px_34px_rgba(249,115,22,0.22)] hover:bg-shop-secondary-hover',
      outline: 'border border-shop-border bg-white text-shop-text hover:border-shop-primary hover:text-shop-primary',
      ghost: 'bg-transparent text-shop-text-muted hover:bg-shop-surface-muted hover:text-shop-text',
    };
    const sizes: Record<ButtonSize, string> = {
      sm: 'rounded-xl px-4 py-2 text-sm',
      md: 'rounded-2xl px-5 py-3 text-sm',
      lg: 'rounded-2xl px-6 py-3.5 text-base',
    };

    return [
      base,
      variants[this.variant()],
      sizes[this.size()],
      this.block() ? 'w-full' : '',
    ];
  });
}

// frontend/src/shared/components/ui/Button.tsx
import type { ButtonHTMLAttributes, ReactNode } from "react";
import { cn } from "@/shared/lib/cn";

type ButtonVariant = "primary" | "secondary" | "ghost" | "danger" | "accent" | "outline";
type ButtonSize = "sm" | "md" | "lg";

type ButtonProps = ButtonHTMLAttributes<HTMLButtonElement> & {
  variant?: ButtonVariant;
  size?: ButtonSize;
  isLoading?: boolean;
  leadingIcon?: ReactNode;
  trailingIcon?: ReactNode;
};

const variantClasses: Record<ButtonVariant, string> = {
  primary:
    "bg-spanish-green-700 text-white shadow-sm shadow-spanish-green-950/10 hover:bg-spanish-green-600",
  secondary:
    "border border-spanish-green-200 bg-white text-spanish-green-800 hover:border-spanish-green-300 hover:bg-spanish-green-50",
  ghost: "text-spanish-green-700 hover:bg-spanish-green-100",
  danger: "bg-red-600 text-white shadow-sm shadow-red-950/10 hover:bg-red-500",
  accent: "bg-amber-600 text-white shadow-sm shadow-amber-950/10 hover:bg-amber-500",
  outline: "border border-spanish-green-300 bg-transparent text-spanish-green-800 hover:bg-spanish-green-100",
};

const sizeClasses: Record<ButtonSize, string> = {
  sm: "h-9 px-3 text-sm",
  md: "h-11 px-4 text-sm",
  lg: "h-12 px-5 text-base",
};

export function Button({
  variant = "primary",
  size = "md",
  isLoading = false,
  leadingIcon,
  trailingIcon,
  className,
  disabled,
  children,
  type,
  ...props
}: ButtonProps) {
  const isDisabled = disabled || isLoading;

  return (
    <button
      type={type ?? "button"}
      className={cn(
        "inline-flex items-center justify-center gap-2 rounded-2xl font-semibold transition focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-spanish-green-200 focus-visible:ring-offset-2 focus-visible:ring-offset-white disabled:cursor-not-allowed disabled:opacity-60",
        variantClasses[variant],
        sizeClasses[size],
        className,
      )}
      disabled={isDisabled}
      aria-busy={isLoading || undefined}
      {...props}
    >
      {isLoading ? (
        <span className="size-4 animate-spin rounded-full border-2 border-current border-r-transparent" aria-hidden="true" />
      ) : (
        leadingIcon
      )}
      <span>{children}</span>
      {!isLoading ? trailingIcon : null}
    </button>
  );
}
