// frontend/src/app/shared/ui/base/checkbox.component.ts
import { ChangeDetectionStrategy, Component, EventEmitter, Output, computed, input } from '@angular/core';
import { createUiId } from './ui-id';
import { FormErrorComponent } from './form-error.component';

@Component({
  selector: 'app-checkbox',
  imports: [FormErrorComponent],
  template: `
    <label class="flex cursor-pointer items-start gap-3 rounded-2xl border border-shop-border bg-white px-4 py-3 transition has-[:focus-visible]:border-shop-primary has-[:focus-visible]:ring-2 has-[:focus-visible]:ring-shop-primary/10">
      <input
        [id]="id()"
        type="checkbox"
        [checked]="checked()"
        [disabled]="disabled()"
        [required]="required()"
        [attr.aria-invalid]="isInvalid() ? 'true' : null"
        [attr.aria-describedby]="describedBy() || null"
        class="mt-1 h-4 w-4 rounded border-shop-border text-shop-primary focus-visible:ring-2 focus-visible:ring-shop-primary focus-visible:ring-offset-2 focus-visible:ring-offset-white disabled:cursor-not-allowed disabled:opacity-60"
        (change)="handleChange($event)"
        (blur)="blurred.emit()"
      />

      <span class="min-w-0">
        <span class="block text-sm font-semibold text-shop-text">
          {{ label() }}
          @if (required()) {
            <span class="ml-1 text-shop-danger" aria-hidden="true">*</span>
          }
        </span>

        @if (hint()) {
          <span [id]="hintId()" class="mt-1 block text-sm text-shop-text-muted">{{ hint() }}</span>
        }

        <app-form-error [id]="errorId()" [error]="error()" />
      </span>
    </label>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class CheckboxComponent {
  readonly id = input<string>(createUiId('shop-checkbox'));
  readonly label = input.required<string>();
  readonly checked = input(false);
  readonly hint = input('');
  readonly error = input<string | readonly string[] | null>(null);
  readonly disabled = input(false);
  readonly required = input(false);

  @Output() readonly checkedChange = new EventEmitter<boolean>();
  @Output() readonly blurred = new EventEmitter<void>();

  protected readonly hintId = computed(() => `${this.id()}-hint`);
  protected readonly errorId = computed(() => `${this.id()}-error`);
  protected readonly isInvalid = computed(() => Boolean(this.error()));
  protected readonly describedBy = computed(() => {
    const describedBy: string[] = [];

    if (this.hint()) {
      describedBy.push(this.hintId());
    }

    if (this.error()) {
      describedBy.push(this.errorId());
    }

    return describedBy.join(' ');
  });

  handleChange(event: Event): void {
    const target = event.target as HTMLInputElement;
    this.checkedChange.emit(target.checked);
  }
}

// frontend/src/shared/components/ui/Checkbox.tsx
import type { InputHTMLAttributes, ReactNode } from "react";
import { useId } from "react";
import { cn } from "@/shared/lib/cn";

type CheckboxProps = Omit<InputHTMLAttributes<HTMLInputElement>, "type"> & {
  label: ReactNode;
  hint?: string;
  error?: string;
};

export function Checkbox({ label, hint, error, className, id, ...props }: CheckboxProps) {
  const autoId = useId();
  const checkboxId = id ?? autoId;
  const message = error ?? hint;

  return (
    <div className="block">
      <label
        htmlFor={checkboxId}
        className={cn(
          "flex cursor-pointer items-start gap-3 rounded-2xl border bg-white px-4 py-3 transition",
          error ? "border-red-300" : "border-spanish-green-200 hover:bg-spanish-green-50",
          className,
        )}
      >
        <input
          id={checkboxId}
          type="checkbox"
          className="mt-1 size-4 rounded border-spanish-green-300 text-spanish-green-700 focus-visible:ring-4 focus-visible:ring-spanish-green-200 focus-visible:ring-offset-2 focus-visible:ring-offset-white"
          aria-invalid={error ? true : undefined}
          aria-describedby={message ? `${checkboxId}-message` : undefined}
          {...props}
        />
        <span className="flex-1">
          <span className="block text-sm font-medium text-spanish-green-900">{label}</span>
          {message ? (
            <span id={`${checkboxId}-message`} className={cn("mt-1 block text-xs leading-5", error ? "text-red-600" : "text-spanish-green-600")}>
              {message}
            </span>
          ) : null}
        </span>
      </label>
    </div>
  );
}
