// frontend/src/app/shared/ui/states/empty-state.component.ts
import { ChangeDetectionStrategy, Component, input } from '@angular/core';

@Component({
  selector: 'app-empty-state',
  template: `
    <section
      class="rounded-[2rem] border border-shop-border bg-white p-6 shadow-soft"
      role="status"
      aria-live="polite"
    >
      <div class="mx-auto flex size-14 items-center justify-center rounded-2xl border border-dashed border-shop-primary/30 bg-shop-primary-soft text-2xl font-black text-shop-primary" aria-hidden="true">
        0
      </div>

      <div class="mt-5 space-y-2 text-center">
        <p class="text-xs font-black uppercase tracking-[0.24em] text-shop-primary">
          {{ eyebrow() }}
        </p>
        <h2 class="text-2xl font-black tracking-tight text-shop-text">
          {{ title() }}
        </h2>
        @if (description()) {
          <p class="mx-auto max-w-2xl text-sm leading-6 text-shop-text-muted">
            {{ description() }}
          </p>
        }
      </div>

      @if (hasProjectedContent) {
        <div class="mt-6 flex flex-wrap justify-center gap-3">
          <ng-content />
        </div>
      }
    </section>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class EmptyStateComponent {
  readonly eyebrow = input('Sem resultados');
  readonly title = input('Nada encontrado');
  readonly description = input('');
  readonly hasProjectedContent = true;
}

// frontend/src/shared/components/ui/EmptyState.tsx
import type { ReactNode } from "react";
import { Badge } from "@/shared/components/ui/Badge";
import { Button } from "@/shared/components/ui/Button";
import { Card } from "@/shared/components/ui/Card";

type EmptyTone = "empty" | "error" | "success";

type EmptyAction = {
  label: string;
  onClick: () => void;
  variant?: "primary" | "secondary" | "ghost" | "danger" | "accent" | "outline";
};

type EmptyStateProps = {
  tone?: EmptyTone;
  title: string;
  description: string;
  action?: EmptyAction;
  secondaryAction?: EmptyAction;
  icon?: ReactNode;
};

const toneMeta: Record<EmptyTone, { badge: string; label: string }> = {
  empty: { badge: "Aguardando dados", label: "Sem resultados" },
  error: { badge: "Falha na carga", label: "Erro" },
  success: { badge: "Pronto", label: "Sucesso" },
};

export function EmptyState({
  tone = "empty",
  title,
  description,
  action,
  secondaryAction,
  icon,
}: EmptyStateProps) {
  const meta = toneMeta[tone];

  return (
    <Card role={tone === "error" ? "alert" : "status"} aria-live={tone === "error" ? "assertive" : "polite"} className="border-dashed border-spanish-green-300 bg-spanish-green-50/70">
      <div className="flex flex-col items-start gap-5 p-6 sm:p-8">
        <Badge variant={tone === "error" ? "danger" : tone === "success" ? "success" : "neutral"}>
          {meta.badge}
        </Badge>
        <div className="flex w-full flex-col gap-2 sm:flex-row sm:items-start sm:justify-between">
          <div className="max-w-2xl space-y-2">
            <h3 className="text-xl font-semibold tracking-tight text-spanish-green-950">{title}</h3>
            <p className="text-sm leading-6 text-spanish-green-700">{description}</p>
          </div>
          {icon ? <div className="text-spanish-green-500">{icon}</div> : null}
        </div>
        {action || secondaryAction ? (
          <div className="flex flex-wrap gap-3">
            {action ? (
              <Button variant={action.variant ?? "primary"} onClick={action.onClick}>
                {action.label}
              </Button>
            ) : null}
            {secondaryAction ? (
              <Button variant={secondaryAction.variant ?? "secondary"} onClick={secondaryAction.onClick}>
                {secondaryAction.label}
              </Button>
            ) : null}
          </div>
        ) : null}
      </div>
    </Card>
  );
}
