// frontend/src/features/orders/pages/OrderDetailPage.tsx
import type { ReactNode } from 'react'
import { useParams } from 'react-router-dom'

import { AppError } from '../../../shared/errors/appError'
import { Button } from '../../../shared/ui/buttons/Button'
import { Skeleton } from '../../../shared/ui/states/Skeleton'
import { calculateOrderTotal, getOrderStatusLabel } from '../formatting/orderPresentation'
import { useOrderDetailQuery } from '../queries/useOrderDetailQuery'
import { parseOrderId } from '../routing/orderId'

const currency = new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' })
const dateTime = new Intl.DateTimeFormat('pt-BR', { dateStyle: 'long', timeStyle: 'short' })

function PageState({
  title,
  description,
  action,
}: {
  title: string
  description: string
  action?: ReactNode
}) {
  return (
    <div className="surface flex flex-col items-center px-6 py-10 text-center">
      <h1 className="text-xl font-semibold text-zinc-100 sm:text-2xl">{title}</h1>
      <p className="mt-2 max-w-md text-sm text-zinc-400">{description}</p>
      {action ? <div className="mt-6">{action}</div> : null}
    </div>
  )
}

function NotFoundState() {
  return <PageState title="Pedido não encontrado" description="Verifique o endereço ou consulte seus pedidos." />
}

export function OrderDetailPage() {
  const { pedidoId } = useParams()
  const orderId = parseOrderId(pedidoId)
  const query = useOrderDetailQuery(orderId)

  if (orderId === undefined) {
    return <section className="container-page py-8 sm:py-10"><NotFoundState /></section>
  }

  if (query.isPending) {
    return (
      <section className="container-page py-8 sm:py-10">
        <div role="status" aria-label="Carregando pedido" aria-live="polite" className="min-h-96 space-y-4">
          <span className="sr-only">Carregando pedido…</span>
          <Skeleton className="h-12 w-64" />
          <Skeleton className="h-52 w-full" />
          <Skeleton className="h-40 w-full" />
        </div>
      </section>
    )
  }

  if (query.isError) {
    if (query.error instanceof AppError && query.error.status === 404) {
      return <section className="container-page py-8 sm:py-10"><NotFoundState /></section>
    }
    return (
      <section className="container-page py-8 sm:py-10">
        <PageState
          title="Não foi possível carregar o pedido"
          description="Ocorreu um erro ao consultar os dados confirmados deste pedido."
          action={<Button onClick={() => void query.refetch()}>Tentar novamente</Button>}
        />
      </section>
    )
  }

  const order = query.data
  return (
    <section className="container-page py-8 sm:py-10" aria-labelledby="order-title">
      <header className="mb-6">
        <h1 id="order-title" className="text-2xl font-bold text-zinc-50 sm:text-3xl">Pedido {order.id}</h1>
        <p className="mt-2 text-sm text-zinc-400">Realizado em {dateTime.format(new Date(order.createdAt))}</p>
      </header>

      <div className="grid gap-6 lg:grid-cols-2">
        <section className="surface p-4 sm:p-6" aria-labelledby="order-summary-title">
          <h2 id="order-summary-title" className="text-lg font-semibold text-zinc-50">Resumo</h2>
          <dl className="mt-4 grid grid-cols-[auto_1fr] gap-x-4 gap-y-3 text-sm">
            <dt className="text-zinc-400">Status</dt><dd className="font-medium text-zinc-100">{getOrderStatusLabel(order.status)}</dd>
            <dt className="text-zinc-400">Pagamento</dt><dd className="font-medium text-zinc-100">{order.paymentMethod}</dd>
          </dl>
        </section>

        <section className="surface p-4 sm:p-6" aria-labelledby="delivery-title">
          <h2 id="delivery-title" className="text-lg font-semibold text-zinc-50">Endereço de entrega</h2>
          <dl className="mt-4 space-y-2 text-sm text-zinc-200">
            <div><dt className="sr-only">Logradouro e número</dt><dd>{order.deliveryAddress.logradouro}, {order.deliveryAddress.numero}</dd></div>
            {order.deliveryAddress.complemento ? <div><dt className="sr-only">Complemento</dt><dd>{order.deliveryAddress.complemento}</dd></div> : null}
            <div><dt className="sr-only">Bairro</dt><dd>{order.deliveryAddress.bairro}</dd></div>
            <div><dt className="sr-only">Cidade e estado</dt><dd>{order.deliveryAddress.cidade} - {order.deliveryAddress.uf}</dd></div>
            <div><dt className="sr-only">CEP</dt><dd>CEP {order.deliveryAddress.cep}</dd></div>
          </dl>
        </section>
      </div>

      <section className="surface mt-6 p-4 sm:p-6" aria-labelledby="items-title">
        <h2 id="items-title" className="text-lg font-semibold text-zinc-50">Itens confirmados</h2>
        <ul className="mt-4 divide-y divide-zinc-800">
          {order.items.map((item) => (
            <li key={item.itemId} className="py-4">
              <div><p className="font-medium text-zinc-100">Produto {item.productId}</p><p className="text-sm text-zinc-400">Quantidade: {item.quantity} · {currency.format(item.unitPrice)} cada</p></div>
            </li>
          ))}
        </ul>
        <div className="mt-4 flex items-center justify-between border-t border-zinc-700 pt-4 text-lg font-bold text-zinc-50"><span>Total</span><span>{currency.format(calculateOrderTotal(order.items))}</span></div>
      </section>
    </section>
  )
}

// frontend/src/app/domains/customer/order-detail-page.component.ts
import { ChangeDetectionStrategy, Component, OnDestroy, OnInit } from '@angular/core';
import { RouterLink } from '@angular/router';

import { PageContainerComponent } from '@shared/ui/page-container.component';
import { EmptyStateComponent } from '@shared/ui/states/empty-state.component';

import { createOrderDetailPageContext } from './order-detail-page.context';

@Component({
  selector: 'app-order-detail-page',
  imports: [EmptyStateComponent, PageContainerComponent, RouterLink],
  template: `
    <app-page-container [wide]="true">
      <section class="space-y-6">
        <div class="rounded-[2rem] border border-shop-border bg-white p-6 shadow-soft lg:p-10">
          <span class="inline-flex rounded-full bg-shop-primary-soft px-3 py-1 text-xs font-black uppercase tracking-[0.24em] text-shop-primary">
            Pedido
          </span>

          <div class="mt-5 flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between">
            <div>
              <h1 class="text-3xl font-black tracking-tight text-shop-text lg:text-4xl">
                Detalhe do pedido #{{ context.pedidoId() }}
              </h1>
              <p class="mt-3 max-w-2xl text-sm leading-6 text-shop-text-muted lg:text-base">
                Consulte os dados do pedido, os itens comprados e o resumo do pagamento.
              </p>
            </div>

            <a
              routerLink="/account/orders"
              class="inline-flex items-center justify-center rounded-2xl border border-shop-border px-5 py-3 text-sm font-bold text-shop-text transition hover:border-shop-primary hover:text-shop-primary"
            >
              Voltar para pedidos
            </a>
          </div>
        </div>

        @if (context.isLoadingOrder()) {
          <app-empty-state
            eyebrow="Pedido"
            title="Carregando pedido"
            description="Estamos buscando os detalhes do pedido selecionado."
          />
        } @else if (context.orderError()) {
          <app-empty-state
            eyebrow="Pedido"
            title="Nao foi possivel carregar o pedido"
            [description]="context.orderError()"
          />
        } @else if (context.hasOrder()) {
          <div class="space-y-6">
            <article class="rounded-[2rem] border border-shop-border bg-white p-6 shadow-soft lg:p-8">
              <div class="grid gap-4 md:grid-cols-2 xl:grid-cols-4">
                <div class="rounded-2xl bg-shop-surface-muted p-4">
                  <p class="text-sm font-medium text-shop-text-muted">Status</p>
                  <p class="mt-1 text-base font-bold text-shop-text">{{ context.order()?.status }}</p>
                </div>

                <div class="rounded-2xl bg-shop-surface-muted p-4">
                  <p class="text-sm font-medium text-shop-text-muted">Data do pedido</p>
                  <p class="mt-1 text-base font-bold text-shop-text">{{ context.order()?.dataPedido }}</p>
                </div>

                <div class="rounded-2xl bg-shop-surface-muted p-4">
                  <p class="text-sm font-medium text-shop-text-muted">Pagamento</p>
                  <p class="mt-1 text-base font-bold text-shop-text">{{ context.order()?.formaPagamento }}</p>
                </div>

                <div class="rounded-2xl bg-shop-surface-muted p-4">
                  <p class="text-sm font-medium text-shop-text-muted">Pedido</p>
                  <p class="mt-1 text-base font-bold text-shop-text">#{{ context.order()?.pedidoId }}</p>
                </div>
              </div>
            </article>

            <article class="rounded-[2rem] border border-shop-border bg-white p-6 shadow-soft lg:p-8">
              <p class="text-xs font-black uppercase tracking-[0.24em] text-shop-text-light">Itens do pedido</p>

              <div class="mt-5 space-y-3">
                @for (item of context.order()?.items ?? []; track item.itemId) {
                  <div class="flex flex-col gap-2 rounded-2xl border border-shop-border bg-shop-surface-muted p-4 sm:flex-row sm:items-center sm:justify-between">
                    <div>
                      <p class="font-semibold text-shop-text">Produto #{{ item.produtoId }}</p>
                      <p class="text-sm text-shop-text-muted">Quantidade: {{ item.quantidade }}</p>
                    </div>

                    <p class="text-sm font-bold text-shop-price">
                      R$ {{ item.valorUnitario }}
                    </p>
                  </div>
                }
              </div>
            </article>

            <article class="rounded-[2rem] border border-shop-border bg-white p-6 shadow-soft lg:p-8">
              <p class="text-xs font-black uppercase tracking-[0.24em] text-shop-text-light">Endere&ccedil;o de entrega</p>

              <div class="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-3">
                <div class="rounded-2xl bg-shop-surface-muted p-4">
                  <p class="text-sm font-medium text-shop-text-muted">Logradouro</p>
                  <p class="mt-1 font-bold text-shop-text">{{ context.order()?.enderecoEntrega?.logradouro }}</p>
                </div>
                <div class="rounded-2xl bg-shop-surface-muted p-4">
                  <p class="text-sm font-medium text-shop-text-muted">Numero</p>
                  <p class="mt-1 font-bold text-shop-text">{{ context.order()?.enderecoEntrega?.numero }}</p>
                </div>
                <div class="rounded-2xl bg-shop-surface-muted p-4">
                  <p class="text-sm font-medium text-shop-text-muted">Complemento</p>
                  <p class="mt-1 font-bold text-shop-text">{{ context.order()?.enderecoEntrega?.complemento || 'Nao informado' }}</p>
                </div>
                <div class="rounded-2xl bg-shop-surface-muted p-4">
                  <p class="text-sm font-medium text-shop-text-muted">Bairro</p>
                  <p class="mt-1 font-bold text-shop-text">{{ context.order()?.enderecoEntrega?.bairro }}</p>
                </div>
                <div class="rounded-2xl bg-shop-surface-muted p-4">
                  <p class="text-sm font-medium text-shop-text-muted">Cidade</p>
                  <p class="mt-1 font-bold text-shop-text">{{ context.order()?.enderecoEntrega?.cidade }}</p>
                </div>
                <div class="rounded-2xl bg-shop-surface-muted p-4">
                  <p class="text-sm font-medium text-shop-text-muted">UF / CEP</p>
                  <p class="mt-1 font-bold text-shop-text">{{ context.order()?.enderecoEntrega?.uf }} - {{ context.order()?.enderecoEntrega?.cep }}</p>
                </div>
              </div>
            </article>
          </div>
        } @else {
          <app-empty-state
            eyebrow="Pedido"
            title="Pedido nao encontrado"
            description="Nenhum detalhe foi retornado para o identificador informado."
          />
        }
      </section>
    </app-page-container>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class OrderDetailPageComponent implements OnInit, OnDestroy {
  protected readonly context = createOrderDetailPageContext();

  ngOnInit(): void {
    this.context.loadOrderDetail();
  }

  ngOnDestroy(): void {
    this.context.clearOrderDetail();
  }
}
